### ISSUE TITLE
Allow the use of dupers for farms

### ISSUE THREAD

**Issue by piplup55** [framewiki/minecraft-server#4]
tnt/carpet dupers are used in some farms to list afew

https://youtu.be/Un-opjPr9LU
https://youtu.be/Bjg1_GEPdDk
https://youtu.be/3-p24fM373w

there are many more uses for these dupers

**Comment by Morpheus636** [comment]
Unfortunately there is no way to enable just TNT duping without also enabling other dupes which is off the table. Unless that changes, TNT dupes will remain patched.
